const STORAGE_KEY = "daily-practice-data-v1";
const SETTINGS_KEY = "daily-practice-settings-v1";
const defaultHabits = [
  { id: "read", name: "阅读 20 分钟", description: "给自己一段安静的输入时间。", color: "rust" },
  { id: "water", name: "喝水 8 杯", description: "照顾身体，是最基础的自律。", color: "forest" },
  { id: "move", name: "运动 30 分钟", description: "让身体先动起来，情绪会跟上。", color: "gold" },
  { id: "english", name: "学习英语", description: "每天积累一点，世界就多一扇窗。", color: "rust" },
  { id: "sleep", name: "23:30 前睡觉", description: "把明天的精神，留给今天准备好。", color: "forest" }
];
const quotes = ["“完成不是终点，\n是给明天的信。”", "“慢一点没有关系，\n只要还在向前。”", "“你正在成为，\n自己可以依靠的人。”", "“把小事做好，\n生活会开始回应。”"];
const weekdays = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];
let data = loadData();
let settings = JSON.parse(localStorage.getItem(SETTINGS_KEY) || "{}");
let viewDate = new Date();
let selectedColor = "rust";

function localDate(date = new Date()) { const y = date.getFullYear(); const m = String(date.getMonth() + 1).padStart(2, "0"); const d = String(date.getDate()).padStart(2, "0"); return `${y}-${m}-${d}`; }
function parseDate(key) { const [y, m, d] = key.split("-").map(Number); return new Date(y, m - 1, d); }
function loadData() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (saved) return { habits: saved.habits?.length ? saved.habits : defaultHabits, logs: saved.logs || {}, notes: saved.notes || {}, goals: saved.goals || [], goalLogs: saved.goalLogs || {}, updatedAt: saved.updatedAt || null }; } catch (_) {} return { habits: defaultHabits, logs: {}, notes: {}, goals: [], goalLogs: {}, updatedAt: null }; }
function persist() { data.updatedAt = new Date().toISOString(); localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); updateAll(); }
function todayLog() { return data.logs[localDate()] || {}; }
function completionFor(key) { const log = data.logs[key] || {}; const total = data.habits.length; return total ? data.habits.filter(h => log[h.id]).length / total : 0; }
function allDone(key) { return data.habits.length > 0 && completionFor(key) === 1; }
function streak() { let cursor = new Date(); let count = 0; if (!allDone(localDate(cursor))) cursor.setDate(cursor.getDate() - 1); while (allDone(localDate(cursor))) { count++; cursor.setDate(cursor.getDate() - 1); } return count; }
function monthCompletion(date = new Date()) { const y = date.getFullYear(); const m = date.getMonth(); const days = new Date(y, m + 1, 0).getDate(); let total = 0; for (let i = 1; i <= days; i++) total += completionFor(`${y}-${String(m + 1).padStart(2, "0")}-${String(i).padStart(2, "0")}`); return days ? Math.round(total / days * 100) : 0; }
function formatDate(date) { return `${date.getFullYear()} / ${String(date.getMonth() + 1).padStart(2, "0")} / ${String(date.getDate()).padStart(2, "0")} · ${weekdays[date.getDay()]}`; }
function updateAll() { renderToday(); renderWeek(); renderCalendar(); renderManager(); renderGoals(); renderTodayGoals(); renderRail(); }

function renderToday() {
  const key = localDate(); const log = data.logs[key] || {}; const done = data.habits.filter(h => log[h.id]).length; const percent = data.habits.length ? Math.round(done / data.habits.length * 100) : 0;
  document.getElementById("dateStamp").textContent = formatDate(new Date()); document.getElementById("todayNavCount").textContent = `${done}/${data.habits.length}`; document.getElementById("streakNumber").textContent = streak(); document.getElementById("progressValue").textContent = `${percent}%`; document.getElementById("progressRing").style.background = `conic-gradient(var(--rust) ${percent * 3.6}deg, var(--paper-deep) 0deg)`;
  document.getElementById("todayHabitList").innerHTML = data.habits.length ? data.habits.map(h => `<div class="habit-row ${log[h.id] ? "done" : ""}"><button class="habit-check" data-toggle-habit="${h.id}" aria-label="${log[h.id] ? "取消" : "完成"}${h.name}">${log[h.id] ? "✓" : ""}</button><span class="habit-name">${escapeHtml(h.name)}</span><span class="habit-meta">${log[h.id] ? "DONE" : "待完成"}</span></div>`).join("") : `<div class="empty-state">还没有习惯，从右上角新建一个吧。</div>`;
  const note = document.getElementById("dailyNote"); if (document.activeElement !== note) note.value = data.notes[key] || "";
  document.getElementById("quoteText").innerHTML = quotes[new Date().getDate() % quotes.length].replace("\n", "<br />");
}
function renderWeek() { const now = new Date(); const start = new Date(now); start.setDate(now.getDate() - 6); let sum = 0; document.getElementById("weekBars").innerHTML = Array.from({ length: 7 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); const value = Math.round(completionFor(localDate(d)) * 100); sum += value; return `<div class="week-bar-wrap"><div class="week-bar ${localDate(d) === localDate() ? "today" : ""}" style="height:${Math.max(value, 6)}%" title="${localDate(d)} ${value}%"></div><span>${["日", "一", "二", "三", "四", "五", "六"][d.getDay()]}</span></div>`; }).join(""); document.getElementById("weekScore").textContent = `${Math.round(sum / 7)}%`; }
function renderCalendar() { const y = viewDate.getFullYear(); const m = viewDate.getMonth(); document.getElementById("monthTitle").textContent = `${y} 年 ${String(m + 1).padStart(2, "0")} 月`; const first = new Date(y, m, 1); const days = new Date(y, m + 1, 0).getDate(); const offset = (first.getDay() + 6) % 7; const prevDays = new Date(y, m, 0).getDate(); let cells = []; for (let i = 0; i < 42; i++) { const day = i - offset + 1; const date = day < 1 ? new Date(y, m - 1, prevDays + day) : day > days ? new Date(y, m + 1, day - days) : new Date(y, m, day); const key = localDate(date); const inMonth = date.getMonth() === m; const percent = Math.round(completionFor(key) * 100); cells.push(`<div class="calendar-day ${inMonth ? "" : "muted"} ${key === localDate() ? "today" : ""}" title="${key}" data-calendar-date="${key}"><span class="calendar-day-number">${date.getDate()}</span><div class="day-dots">${data.habits.map(h => `<i class="day-dot ${data.logs[key]?.[h.id] ? "done" : ""}"></i>`).join("")}</div></div>`); } document.getElementById("calendarGrid").innerHTML = cells.join(""); }
function renderManager() { document.getElementById("habitManager").innerHTML = data.habits.map((h, i) => `<div class="manager-row"><i class="manager-color ${h.color}"></i><div><span class="manager-title">${escapeHtml(h.name)}</span><span class="manager-description">${escapeHtml(h.description || "")}</span></div><div class="manager-actions"><button class="small-button" data-edit-habit="${h.id}">编辑</button><button class="small-button" data-delete-habit="${h.id}">删除</button></div></div>`).join(""); }
function goalProgress(goal) { const start = parseDate(goal.start); const end = parseDate(goal.end); const today = new Date(); today.setHours(0, 0, 0, 0); const through = today < end ? today : end; if (through < start) return { percent: 0, doneDays: 0, totalDays: 0, status: "未开始" }; let doneDays = 0; let totalDays = 0; for (const cursor = new Date(start); cursor <= through; cursor.setDate(cursor.getDate() + 1)) { totalDays++; if (data.goalLogs?.[localDate(cursor)]?.[goal.id]) doneDays++; } const percent = totalDays ? Math.round(doneDays / totalDays * 100) : 0; return { percent, doneDays, totalDays, status: today > end ? "已结束" : "进行中" }; }
function renderGoals() { const list = document.getElementById("goalsList"); const empty = document.getElementById("goalsEmpty"); if (!list || !empty) return; data.goals = data.goals || []; empty.classList.toggle("hidden", data.goals.length > 0); list.innerHTML = data.goals.map(goal => { const progress = goalProgress(goal); const habits = (goal.habitIds || []).map(id => data.habits.find(h => h.id === id)?.name).filter(Boolean).join("、") || "全部习惯"; return `<article class="goal-card"><div class="goal-card-top"><div><span class="eyebrow">${progress.status}</span><h2>${escapeHtml(goal.name)}</h2><p>${escapeHtml(goal.description || "")}</p></div><strong class="goal-percent">${progress.percent}%</strong></div><div class="goal-progress"><span style="width:${progress.percent}%"></span></div><div class="goal-meta"><span>${goal.start} → ${goal.end}</span><span>${progress.doneDays}/${progress.totalDays} 天完成</span></div><div class="goal-habits">关联习惯：${escapeHtml(habits)}</div></article>`; }).join(""); }
function renderGoals() { const list = document.getElementById("goalsList"); const empty = document.getElementById("goalsEmpty"); if (!list || !empty) return; data.goals = data.goals || []; empty.classList.toggle("hidden", data.goals.length > 0); list.innerHTML = data.goals.map(goal => { const progress = goalProgress(goal); return `<article class="goal-card"><div class="goal-card-top"><div><span class="eyebrow">${progress.status}</span><h2>${escapeHtml(goal.name)}</h2><p>${escapeHtml(goal.description || "")}</p></div><strong class="goal-percent">${progress.percent}%</strong></div><div class="goal-progress"><span style="width:${progress.percent}%"></span></div><div class="goal-meta"><span>${goal.start} → ${goal.end}</span><span>${progress.doneDays}/${progress.totalDays} 天完成</span></div><div class="goal-actions"><button class="small-button" data-edit-goal="${goal.id}">编辑</button><button class="small-button" data-delete-goal="${goal.id}">删除</button></div></article>`; }).join(""); }
function renderTodayGoals() { const list = document.getElementById("todayGoalsList"); const card = document.getElementById("todayGoalsCard"); if (!list || !card) return; const today = localDate(); const goals = (data.goals || []).filter(goal => today >= goal.start && today <= goal.end); card.classList.toggle("hidden", goals.length === 0); list.innerHTML = goals.map(goal => { const done = Boolean(data.goalLogs?.[today]?.[goal.id]); const progress = goalProgress(goal); return `<div class="today-goal-row ${done ? "done" : ""}"><button class="habit-check" data-toggle-goal="${goal.id}" aria-label="${done ? "取消完成" : "完成"}${escapeHtml(goal.name)}">${done ? "✓" : ""}</button><div><strong>${escapeHtml(goal.name)}</strong><span>${goal.end} 结束 · 当前 ${progress.percent}%</span></div></div>`; }).join(""); }
function renderRail() { const now = new Date(); const months = ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"]; document.getElementById("railMonth").textContent = months[now.getMonth()]; document.getElementById("railDay").textContent = String(now.getDate()).padStart(2, "0"); document.getElementById("railWeekday").textContent = weekdays[now.getDay()]; const month = monthCompletion(); document.getElementById("monthCompletion").textContent = `${month}%`; document.getElementById("monthProgress").style.width = `${month}%`; document.getElementById("railQuote").innerHTML = quotes[(now.getDate() + 1) % quotes.length].replace("\n", "<br />"); const connected = settings.owner && settings.repo && settings.token; document.getElementById("syncMiniStatus").innerHTML = `<span class="status-dot"></span><span>${connected ? "GitHub 已连接" : "仅本地保存"}</span>`; renderYesterdayPending(); }
function renderYesterdayPending() { const box = document.getElementById("yesterdayPending"); if (!box) return; const yesterday = new Date(); yesterday.setDate(yesterday.getDate() - 1); const key = localDate(yesterday); const log = data.logs[key] || {}; const unfinishedHabits = data.habits.filter(h => !log[h.id]); const unfinishedGoals = (data.goals || []).filter(goal => key >= goal.start && key <= goal.end && !data.goalLogs?.[key]?.[goal.id]); const habitsHtml = unfinishedHabits.length ? `<strong>习惯</strong>${unfinishedHabits.map(h => `<span>· ${escapeHtml(h.name)}</span>`).join("")}` : ""; const goalsHtml = unfinishedGoals.length ? `<strong>目标</strong>${unfinishedGoals.map(goal => `<span>· ${escapeHtml(goal.name)}</span>`).join("")}` : ""; box.innerHTML = habitsHtml || goalsHtml ? `${habitsHtml}${goalsHtml}` : `<span class="pending-clear">昨日全部完成 ✓</span>`; }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char])); }
function showView(view) { document.querySelectorAll(".view").forEach(el => el.classList.toggle("hidden", el.id !== `${view}View`)); document.querySelectorAll(".nav-item").forEach(el => el.classList.toggle("active", el.dataset.view === view)); }
function toast(message) { const el = document.getElementById("toast"); el.textContent = message; el.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove("show"), 2200); }
function openHabitModal(habit = null) { document.getElementById("habitForm").reset(); document.getElementById("habitEditId").value = habit?.id || ""; document.getElementById("habitName").value = habit?.name || ""; document.getElementById("habitDesc").value = habit?.description || ""; selectedColor = habit?.color || "rust"; document.querySelectorAll(".color-option").forEach(option => option.classList.toggle("active", option.dataset.color === selectedColor)); document.getElementById("habitModalTitle").textContent = habit ? "修改习惯" : "给自己一个小约定"; document.getElementById("habitSubmit").innerHTML = habit ? "保存修改" : "<span>＋</span> 保存习惯"; document.getElementById("habitFeedback").textContent = ""; document.getElementById("habitModal").classList.remove("hidden"); document.getElementById("habitName").focus(); }
function closeHabitModal() { document.getElementById("habitModal").classList.add("hidden"); }
function openGoalModal(goal = null) { const today = localDate(); document.getElementById("goalForm").reset(); document.getElementById("goalEditId").value = goal?.id || ""; document.getElementById("goalName").value = goal?.name || ""; document.getElementById("goalDesc").value = goal?.description || ""; document.getElementById("goalStart").value = goal?.start || today; const end = new Date(); end.setDate(end.getDate() + 30); document.getElementById("goalEnd").value = goal?.end || localDate(end); document.getElementById("goalTitle").textContent = goal ? "修改目标" : "新建长远目标"; document.getElementById("goalFeedback").textContent = ""; document.getElementById("goalModal").classList.remove("hidden"); document.getElementById("goalName").focus(); }
function closeGoalModal() { document.getElementById("goalModal").classList.add("hidden"); }
function openSettings() { document.getElementById("githubOwner").value = settings.owner || ""; document.getElementById("githubRepo").value = settings.repo || ""; document.getElementById("githubToken").value = settings.token || ""; document.getElementById("githubPath").value = settings.path || "data/checkins.json"; document.getElementById("settingsFeedback").textContent = ""; document.getElementById("settingsModal").classList.remove("hidden"); }
function closeSettings() { document.getElementById("settingsModal").classList.add("hidden"); }
function toBase64(text) { const bytes = new TextEncoder().encode(text); let binary = ""; bytes.forEach(byte => binary += String.fromCharCode(byte)); return btoa(binary); }
function fromBase64(value) { const binary = atob(value.replace(/\n/g, "")); return new TextDecoder().decode(Uint8Array.from(binary, char => char.charCodeAt(0))); }
async function githubRequest(method, body) { const endpoint = `https://api.github.com/repos/${encodeURIComponent(settings.owner)}/${encodeURIComponent(settings.repo)}/contents/${settings.path || "data/checkins.json"}`; const response = await fetch(endpoint, { method, headers: { Authorization: `Bearer ${settings.token}`, Accept: "application/vnd.github+json", "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.json(); }
async function syncToGithub() { const button = document.getElementById("syncButton"); button.disabled = true; button.textContent = "同步中…"; try { let sha; try { sha = (await githubRequest("GET")).sha; } catch (error) { if (!String(error.message).startsWith("404")) throw error; } const result = await githubRequest("PUT", { message: `chore: update daily practice ${localDate()}`, content: toBase64(JSON.stringify(data, null, 2)), ...(sha ? { sha } : {}) }); settings.updatedAt = result.commit.committer.date; localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); document.getElementById("settingsFeedback").textContent = "同步成功，数据已写入 GitHub。"; toast("已同步到 GitHub"); renderRail(); } catch (error) { document.getElementById("settingsFeedback").textContent = `同步失败：${error.message}。请检查仓库名、Token 和权限。`; } finally { button.disabled = false; button.textContent = "保存并同步"; } }
async function importFromGithub() { const button = document.getElementById("importButton"); button.disabled = true; button.textContent = "读取中…"; try { const result = await githubRequest("GET"); const imported = JSON.parse(fromBase64(result.content)); if (!imported.habits || !imported.logs) throw new Error("数据文件格式不正确"); data = imported; persist(); document.getElementById("settingsFeedback").textContent = "导入成功，页面已更新。"; toast("已从 GitHub 导入"); } catch (error) { document.getElementById("settingsFeedback").textContent = `导入失败：${error.message}。`; } finally { button.disabled = false; button.textContent = "从 GitHub 导入"; } }

document.addEventListener("click", event => { const toggle = event.target.closest("[data-toggle-habit]"); if (toggle) { const key = localDate(); data.logs[key] = data.logs[key] || {}; data.logs[key][toggle.dataset.toggleHabit] = !data.logs[key][toggle.dataset.toggleHabit]; persist(); return; } const nav = event.target.closest("[data-view]"); if (nav) { showView(nav.dataset.view); return; } if (event.target.closest("[data-open-settings]")) openSettings(); if (event.target.closest("[data-close-settings]")) closeSettings(); const del = event.target.closest("[data-delete-habit]"); if (del) { if (data.habits.length === 1) return toast("至少保留一个习惯"); data.habits = data.habits.filter(h => h.id !== del.dataset.deleteHabit); persist(); toast("习惯已删除"); } const edit = event.target.closest("[data-edit-habit]"); if (edit) { const habit = data.habits.find(h => h.id === edit.dataset.editHabit); if (habit) openHabitModal(habit); return; } const dateCell = event.target.closest("[data-calendar-date]"); if (dateCell && dateCell.dataset.calendarDate === localDate()) showView("today"); });
document.getElementById("dailyNote").addEventListener("input", event => { data.notes[localDate()] = event.target.value; persist(); document.getElementById("noteSaveHint").textContent = "已自动保存"; });
document.getElementById("prevMonth").addEventListener("click", () => { viewDate.setMonth(viewDate.getMonth() - 1); renderCalendar(); }); document.getElementById("nextMonth").addEventListener("click", () => { viewDate.setMonth(viewDate.getMonth() + 1); renderCalendar(); });
 document.getElementById("settingsForm").addEventListener("submit", event => { event.preventDefault(); settings = { owner: document.getElementById("githubOwner").value.trim(), repo: document.getElementById("githubRepo").value.trim(), token: document.getElementById("githubToken").value.trim(), path: document.getElementById("githubPath").value.trim() || "data/checkins.json" }; localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); if (!settings.owner || !settings.repo || !settings.token) { document.getElementById("settingsFeedback").textContent = "已保存本地设置。填写完整 GitHub 信息后才能同步。"; renderRail(); return; } syncToGithub(); }); document.getElementById("importButton").addEventListener("click", () => { if (!settings.owner || !settings.repo || !settings.token) { document.getElementById("settingsFeedback").textContent = "请先填写 GitHub 用户名、仓库名和 Token。"; return; } importFromGithub(); }); document.getElementById("newHabitButton").addEventListener("click", openHabitModal); document.getElementById("openHabitModal")?.addEventListener("click", openHabitModal); document.getElementById("closeHabitModal").addEventListener("click", closeHabitModal); document.getElementById("cancelHabitModal").addEventListener("click", closeHabitModal); document.querySelectorAll(".color-option").forEach(option => option.addEventListener("click", () => { selectedColor = option.dataset.color; document.querySelectorAll(".color-option").forEach(item => item.classList.toggle("active", item === option)); })); document.getElementById("habitForm").addEventListener("submit", event => { event.preventDefault(); const name = document.getElementById("habitName").value.trim(); if (!name) return; data.habits.push({ id: `${Date.now()}`, name, description: document.getElementById("habitDesc").value.trim() || "一个值得持续的小行动。", color: selectedColor }); persist(); closeHabitModal(); toast("新习惯已添加"); });
document.getElementById("newGoalButton").addEventListener("click", () => openGoalModal()); document.querySelectorAll("[data-close-goal]").forEach(button => button.addEventListener("click", closeGoalModal)); document.getElementById("goalForm").addEventListener("submit", event => { event.preventDefault(); const name = document.getElementById("goalName").value.trim(); const start = document.getElementById("goalStart").value; const end = document.getElementById("goalEnd").value; if (!name || !start || !end || end < start) { document.getElementById("goalFeedback").textContent = "请填写名称，并确保结束日期不早于开始日期。"; return; } const id = document.getElementById("goalEditId").value; const goal = id ? data.goals.find(item => item.id === id) : null; if (goal) { goal.name = name; goal.description = document.getElementById("goalDesc").value.trim(); goal.start = start; goal.end = end; } else { data.goals.push({ id: `${Date.now()}`, name, description: document.getElementById("goalDesc").value.trim(), start, end }); } persist(); closeGoalModal(); showView("goals"); toast(goal ? "目标已修改" : "目标已创建"); });
document.addEventListener("click", event => { const goalToggle = event.target.closest("[data-toggle-goal]"); if (goalToggle) { const key = localDate(); data.goalLogs = data.goalLogs || {}; data.goalLogs[key] = data.goalLogs[key] || {}; data.goalLogs[key][goalToggle.dataset.toggleGoal] = !data.goalLogs[key][goalToggle.dataset.toggleGoal]; persist(); return; } const editGoal = event.target.closest("[data-edit-goal]"); if (editGoal) { const goal = data.goals.find(item => item.id === editGoal.dataset.editGoal); if (goal) openGoalModal(goal); return; } const deleteGoal = event.target.closest("[data-delete-goal]"); if (deleteGoal) { data.goals = data.goals.filter(item => item.id !== deleteGoal.dataset.deleteGoal); persist(); toast("目标已删除"); } });
document.addEventListener("submit", event => { if (event.target.id !== "habitForm") return; event.preventDefault(); event.stopImmediatePropagation(); const name = document.getElementById("habitName").value.trim(); if (!name) return; const id = document.getElementById("habitEditId").value; const habit = id ? data.habits.find(item => item.id === id) : null; const description = document.getElementById("habitDesc").value.trim() || "一个值得持续的小行动。"; if (habit) { habit.name = name; habit.description = description; habit.color = selectedColor; } else data.habits.push({ id: `${Date.now()}`, name, description, color: selectedColor }); persist(); closeHabitModal(); toast(habit ? "习惯已修改" : "新习惯已添加"); }, true);
 updateAll();

